#!/usr/bin/env python3
"""
Derive throughput + area-efficiency from the synth CSVs, emit results/throughput.csv,
the paper figures (results/figures/, needs matplotlib), and paper/tables.tex.

SIMON cores here process ONE block at a time (non-pipelined):
    cycles/block = ceil(T/U) + 2        throughput = BLK * Fmax / cycles
The AES-128 baseline is FULLY PIPELINED (1 block/cycle, Nr+1 latency):
    throughput = BLK * Fmax
Mbps/LUT is the architecture-agnostic efficiency metric used for comparison.
Run:  /tmp/mplvenv/bin/python model/analyze.py
"""
import csv, math, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def consts():
    txt = open(os.path.join(ROOT, "rtl", "simon_consts.svh")).read()
    g = lambda k: int(re.search(rf"{k}\s*=\s*(\d+)", txt).group(1))
    return g("T"), g("BLK")
T, BLK = consts()

def load(name):
    p = os.path.join(ROOT, "results", name)
    if not os.path.exists(p): return None
    return list(csv.DictReader(open(p)))

syn = load("synth_sweep.csv")
aes = load("aes_synth.csv")

# ---- derive throughput / efficiency ----
rows = []
if syn:
    for r in sorted(syn, key=lambda r: int(r["unroll"])):
        U = int(r["unroll"]); lut = int(r["lut"]); fmax = float(r["fmax_mhz"])
        cyc = math.ceil(T / U) + 2
        tput = BLK * fmax / cyc                       # Mb/s  (Fmax in MHz)
        rows.append(dict(U=U, lut=lut, ff=int(r["ff"]), fmax=fmax,
                         power=r["power_w"], cyc=cyc, tput=tput, eff=tput/lut))
    with open(os.path.join(ROOT, "results", "throughput.csv"), "w") as f:
        f.write("unroll,cycles_per_block,lut,ff,fmax_mhz,throughput_mbps,mbps_per_lut\n")
        for d in rows:
            f.write(f"{d['U']},{d['cyc']},{d['lut']},{d['ff']},{d['fmax']:.1f},"
                    f"{d['tput']:.1f},{d['eff']:.3f}\n")
    print(f"T={T} BLK={BLK}")
    print("  U  cyc   LUT   FF   Fmax   Mb/s   Mbps/LUT")
    for d in rows:
        print(f"  {d['U']:>2} {d['cyc']:>4} {d['lut']:>5} {d['ff']:>4} "
              f"{d['fmax']:>6.0f} {d['tput']:>7.0f} {d['eff']:>7.3f}")

aes_row = None
if aes:
    a = aes[0]; lut = int(a["lut"]); fmax = float(a["fmax_mhz"])
    aes_row = dict(lut=lut, ff=int(a["ff"]), fmax=fmax, tput=BLK*fmax, eff=BLK*fmax/lut)
    print(f"\nAES-128 (pipelined): LUT={lut} FF={a['ff']} Fmax={fmax:.0f} "
          f"tput={aes_row['tput']:.0f} Mb/s  {aes_row['eff']:.3f} Mbps/LUT")

# ---- figures ----
try:
    import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
    FIG = os.path.join(ROOT, "results", "figures"); os.makedirs(FIG, exist_ok=True)
    def save(fig, s):
        for e in ("png","pdf"): fig.savefig(os.path.join(FIG,f"{s}.{e}"),bbox_inches="tight",dpi=160)
        plt.close(fig); print(f"wrote results/figures/{s}.png/.pdf")
    if rows:
        U=[d['U'] for d in rows]
        fig,ax=plt.subplots(figsize=(4.3,3.0))
        ax.plot(U,[d['lut'] for d in rows],"o-",label="LUT")
        ax.plot(U,[d['ff'] for d in rows],"s-",label="FF")
        ax.set_xlabel("unroll factor U"); ax.set_ylabel("primitives"); ax.grid(True,ls=":")
        ax2=ax.twinx(); ax2.plot(U,[d['fmax'] for d in rows],"^--",color="green",label="Fmax")
        ax2.set_ylabel("Fmax (MHz)",color="green")
        h1,l1=ax.get_legend_handles_labels(); h2,l2=ax2.get_legend_handles_labels()
        ax.legend(h1+h2,l1+l2,fontsize=8,loc="upper left"); save(fig,"fig_area")

        fig,ax=plt.subplots(figsize=(4.3,3.0))
        ax.plot(U,[d['tput'] for d in rows],"o-",color="C3",label="throughput")
        ax.set_xlabel("unroll factor U"); ax.set_ylabel("throughput (Mb/s)",color="C3"); ax.grid(True,ls=":")
        ax2=ax.twinx(); ax2.plot(U,[d['eff'] for d in rows],"s--",color="C0",label="Mbps/LUT")
        ax2.set_ylabel("efficiency (Mbps/LUT)",color="C0")
        save(fig,"fig_throughput")
except ImportError:
    print("matplotlib not available -> skipped figures (run with /tmp/mplvenv/bin/python)")

# ---- LaTeX tables ----
out=["% AUTO-GENERATED by model/analyze.py"]
if rows:
    part = syn[0]["part"].replace("_","\\_")
    out.append(r"\begin{table}[tb]\centering\setlength{\tabcolsep}{4pt}\footnotesize"
               r"\caption{SIMON128/128 area, $F_{\max}$ and"
               r" throughput vs.\ round-unroll $U$ on %s (OOC place\&route). Zero DSP/BRAM at every point.}"
               r"\label{tab:simon}\begin{tabular}{rrrrrrr}\toprule" % part)
    out.append(r"$U$ & cyc/blk & LUT & FF & $F_{\max}$ & Mb/s & Mbps/LUT\\\midrule")
    for d in rows:
        out.append(f"{d['U']} & {d['cyc']} & {d['lut']} & {d['ff']} & {d['fmax']:.0f} & "
                   f"{d['tput']:.0f} & {d['eff']:.2f}\\\\")
    out.append(r"\bottomrule\end{tabular}\end{table}")
if rows and aes_row:
    best=max(rows,key=lambda d:d['eff'])
    out.append(r"\begin{table}[tb]\centering\setlength{\tabcolsep}{5pt}\footnotesize"
               r"\caption{SIMON128/128 (best-efficiency $U$) vs.\ a"
               r" pipelined AES-128 core, same part.}\label{tab:aes}\begin{tabular}{lrrrr}\toprule")
    out.append(r"design & LUT & FF & Mb/s & Mbps/LUT\\\midrule")
    out.append(f"AES-128 (pipelined) & {aes_row['lut']} & {aes_row['ff']} & "
               f"{aes_row['tput']:.0f} & {aes_row['eff']:.2f}\\\\")
    out.append(f"SIMON ($U{{=}}{best['U']}$) & {best['lut']} & {best['ff']} & "
               f"{best['tput']:.0f} & {best['eff']:.2f}\\\\")
    out.append(r"\bottomrule\end{tabular}\end{table}")
open(os.path.join(ROOT,"paper","tables.tex"),"w").write("\n".join(out)+"\n")
print("wrote paper/tables.tex")
