#!/usr/bin/env python3
"""
Bit-accurate reference model for the SIMON block cipher (encryption).

SINGLE SOURCE OF TRUTH. It:
  1. Implements SIMON (all standard variants) and self-checks against the
     official test vectors from Beaulieu et al. (the SIMON/SPECK paper).
  2. Emits  rtl/simon_consts.svh  (variant params + z constant) for the RTL.
  3. Emits  sim/vectors.hex        (key, plaintext, ciphertext) for the testbench.

Round function (block = 2n bits, words x:upper, y:lower):
    x, y  <-  ( y XOR (ROL(x,1) AND ROL(x,8)) XOR ROL(x,2) XOR k_i ),  x
Key schedule (m key words, T rounds, z-sequence j, c = 2^n - 4):
    k_i = ~k_{i-m} XOR (I XOR ROR1)(ROR3(k_{i-1}) [XOR k_{i-3} if m==4]) XOR z[j][i-m] XOR c
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Five z constant sequences (period 62), MSB-first as in the spec.
Z = [
 "11111010001001010110000111001101111101000100101011000011100110",
 "10001110111110010011000010110101000111011111001001100001011010",
 "10101111011100000011010010011000101000010001111110010110110011",
 "11011011101011000110010111100000010010001010011100110100001111",
 "11010001111001101011011000100000010111000011001010010011101111",
]

# variant -> (n, m, T, j)
VARIANTS = {
    "32_64":   (16, 4, 32, 0),
    "48_72":   (24, 3, 36, 0),
    "48_96":   (24, 4, 36, 1),
    "64_96":   (32, 3, 42, 2),
    "64_128":  (32, 4, 44, 3),
    "96_96":   (48, 2, 52, 2),
    "96_144":  (48, 3, 54, 3),
    "128_128": (64, 2, 68, 2),
    "128_192": (64, 3, 69, 3),
    "128_256": (64, 4, 72, 4),
}

# Official test vectors (key, plaintext, ciphertext) as integers.
OFFICIAL = {
    "32_64":   (0x1918111009080100, 0x65656877, 0xc69be9bb),
    "64_128":  (0x1b1a1918131211100b0a090803020100, 0x656b696c20646e75, 0x44c8fc20b9dfa07a),
    "128_128": (0x0f0e0d0c0b0a09080706050403020100,
                0x6373656420737265_6c6c657661727420, 0x49681b1e1e54fe3f_65aa832af84e0bbc),
}


def rol(v, r, n):  return ((v << r) | (v >> (n - r))) & ((1 << n) - 1)
def ror(v, r, n):  return rol(v, n - r, n)

def key_schedule(key, n, m, T, j):
    mask = (1 << n) - 1
    c = 3                                         # with ~k below this yields 2^n-4 on the word
    k = [(key >> (n * i)) & mask for i in range(m)]   # k[0] = least-significant word
    for i in range(m, T):
        tmp = ror(k[i-1], 3, n)
        if m == 4:
            tmp ^= k[i-3]
        tmp ^= ror(tmp, 1, n)
        zi = int(Z[j][(i - m) % 62])
        k.append((~k[i-m] & mask) ^ tmp ^ zi ^ c)
    return k

def encrypt(key, pt, n, m, T, j):
    mask = (1 << n) - 1
    rk = key_schedule(key, n, m, T, j)
    x = (pt >> n) & mask                          # upper word
    y = pt & mask                                 # lower word
    for i in range(T):
        x, y = (y ^ (rol(x, 1, n) & rol(x, 8, n)) ^ rol(x, 2, n) ^ rk[i]), x
    return (x << n) | y


def selfcheck():
    ok = True
    for name, (key, pt, ct) in OFFICIAL.items():
        n, m, T, j = VARIANTS[name]
        got = encrypt(key, pt, n, m, T, j)
        status = "OK " if got == ct else "FAIL"
        ok &= (got == ct)
        print(f"  [{status}] SIMON{name.replace('_','/')}: "
              f"E(k,pt)={got:0{n//2}x} expect={ct:0{n//2}x}")
    return ok


def emit(variant):
    n, m, T, j = VARIANTS[variant]
    blk = 2 * n
    # consts header
    cpath = os.path.join(ROOT, "rtl", "simon_consts.svh")
    with open(cpath, "w") as f:
        f.write("// AUTO-GENERATED by model/simon_model.py -- DO NOT EDIT.\n")
        f.write("// NOTE: no include guard (module-scoped localparams, re-included per module)\n\n")
        f.write(f"localparam int N     = {n};      // word width\n")
        f.write(f"localparam int M     = {m};      // key words\n")
        f.write(f"localparam int T     = {T};      // rounds\n")
        f.write(f"localparam int BLK   = {blk};    // block width = 2N\n")
        f.write(f"localparam int KEYW  = {m*n};    // key width = M*N\n")
        # GZSEQ[r] = z bit consumed by the on-the-fly key generation AT round r
        # (producing k[r+M]); 0 once r+M>=T (those generated keys are unused).
        # Emit MSB-first: leftmost char is bit T-1, so index GZSEQ[r] gives round r.
        gz = ["1" if ((r + m) < T and Z[j][r % 62] == "1") else "0"
              for r in range(T)]
        f.write(f"localparam logic [T-1:0] GZSEQ = {T}'b{''.join(reversed(gz))};"
                f"  // GZSEQ[r] = key-gen z bit at round r\n")
    # vectors: official + pseudo-random (LCG, deterministic), one per line "key pt ct"
    vpath = os.path.join(ROOT, "sim", "vectors.hex")
    kw = (m * n + 3) // 4
    bw = (blk + 3) // 4
    rows = []
    if variant in OFFICIAL:
        k, p, c = OFFICIAL[variant]
        rows.append((k, p, c))
    state = 0xDEADBEEFCAFEBABE
    keymask = (1 << (m * n)) - 1
    blkmask = (1 << blk) - 1
    for _ in range(200):
        state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        key = 0
        for w in range((m * n + 63) // 64):
            state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
            key = (key << 64) | state
        key &= keymask
        state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        pt = state & blkmask
        if blk > 64:
            state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
            pt = (pt << 64) | (state & ((1 << (blk - 64)) - 1)) if blk > 64 else pt
        pt &= blkmask
        rows.append((key, pt, encrypt(key, pt, n, m, T, j)))
    with open(vpath, "w") as f:
        for k, p, c in rows:
            f.write(f"{k:0{kw}x} {p:0{bw}x} {c:0{bw}x}\n")
    return cpath, vpath, len(rows)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="128_128", choices=list(VARIANTS))
    args = ap.parse_args()
    print("self-check vs official test vectors:")
    if not selfcheck():
        raise SystemExit("MODEL SELF-CHECK FAILED")
    c, v, nrows = emit(args.variant)
    n, m, T, j = VARIANTS[args.variant]
    print(f"\nvariant SIMON{args.variant.replace('_','/')}: n={n} m={m} T={T} z={j} block={2*n}")
    print(f"wrote {os.path.relpath(c, ROOT)}")
    print(f"wrote {os.path.relpath(v, ROOT)}  ({nrows} vectors incl. official)")
