// AUTO-GENERATED by model/simon_model.py -- DO NOT EDIT.
// NOTE: no include guard (module-scoped localparams, re-included per module)

localparam int N     = 64;      // word width
localparam int M     = 2;      // key words
localparam int T     = 68;      // rounds
localparam int BLK   = 128;    // block width = 2N
localparam int KEYW  = 128;    // key width = M*N
localparam logic [T-1:0] GZSEQ = 68'b00010111001101101001111110001000010100011001001011000000111011110101;  // GZSEQ[r] = key-gen z bit at round r
